ai_models:
  provider1: "openai" # Change to "ollama" if using Ollama
  model1: "gpt-4o" # OpenAI model
  provider2: "openai"
  model2: "gpt-4" # Ollama model

conversation:
  max_turns: 20
  summarize_every: 5

database:
  type: "sqlite"
  path: "chat_history.db"

visualization:
  enable: true
  save_as: "conversation_graph.png"

web_ui:
  enable: true
  port: 5000
